export const listData = [
    {
        "id": 1,
        "name": "Garden Bliss",
        "capacity": 150,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 3000,
        "priceBar": 1500,
        "priceCeremony": 500,
        "image": "/venue1.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": false,
        "location": "Al-Azhar Park, Cairo, Egypt",
        "availability": "Available",
        "rate": 4.8,
        "description": "Nestled in the heart of Cairo, Garden Bliss offers a stunning outdoor setting surrounded by lush greenery and beautiful floral arrangements. It's the perfect venue for couples looking to celebrate their special day in a serene and picturesque environment.",
        "contact": "info@gardenbliss.com",
        "venueType": "Garden",
        "latitude": 30.0342,
        "longitude": 31.2364,
        "images": [
            "/garden1.jpg",
            "/garden2.jpg",
            "/garden3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 2,
        "name": "Oceanview Hall",
        "capacity": 200,
        "indoorOutdoor": "Indoor",
        "priceVenue": 5000,
        "priceBar": 2000,
        "priceCeremony": 700,
        "image": "/venue2.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": false,
        "roomsIncluded": true,
        "location": "Hurghada, Red Sea, Egypt",
        "availability": "Available",
        "rate": 4.7,
        "description": "Overlooking the beautiful Red Sea, Oceanview Hall provides a luxurious indoor venue where elegance meets comfort. This venue is ideal for grand celebrations, offering spacious facilities and stunning views that will impress your guests.",
        "contact": "contact@oceanviewhall.com",
        "venueType": "Hall",
        "latitude": 27.2579,
        "longitude": 33.8123,
        "images": [
            "/ocean1.jpg",
            "/ocean2.jpg",
            "/ocean3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 3,
        "name": "Rustic Barn",
        "capacity": 100,
        "indoorOutdoor": "Indoor",
        "priceVenue": 2500,
        "priceBar": 1000,
        "priceCeremony": 400,
        "image": "/venue3.jpg",
        "cateringIncluded": false,
        "cleanUpIncluded": true,
        "roomsIncluded": false,
        "location": "Fayoum Oasis, Egypt",
        "availability": "Available",
        "rate": 4.5,
        "description": "Set in the charming Fayoum Oasis, Rustic Barn exudes a cozy and intimate atmosphere. With its rustic decor and warm ambiance, it's an ideal spot for couples seeking a quaint yet stylish venue for their wedding.",
        "contact": "info@rusticbarn.com",
        "venueType": "Barn",
        "latitude": 29.3039,
        "longitude": 30.8322,
        "images": [
            "/barn1.jpg",
            "/barn2.jpg",
            "/barn3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 4,
        "name": "Elegant Manor",
        "capacity": 300,
        "indoorOutdoor": "Indoor",
        "priceVenue": 7000,
        "priceBar": 2500,
        "priceCeremony": 1000,
        "image": "/venue4.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Zamalek, Cairo, Egypt",
        "availability": "Not Available",
        "rate": 4.9,
        "description": "Elegant Manor is a luxurious venue located in the upscale neighborhood of Zamalek. With its opulent interiors and grand ballrooms, it offers a sophisticated setting for a lavish wedding celebration.",
        "contact": "info@elegantmanor.com",
        "venueType": "Manor",
        "latitude": 30.0621,
        "longitude": 31.2055,
        "images": [
            "/elegant1.jpg",
            "/elegant2.jpg",
            "/elegant3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 5,
        "name": "Sunset Rooftop",
        "capacity": 80,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 4000,
        "priceBar": 1800,
        "priceCeremony": 300,
        "image": "/venue5.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": false,
        "roomsIncluded": false,
        "location": "Maadi, Cairo, Egypt",
        "availability": "Available",
        "rate": 4.6,
        "description": "Perched high above the bustling city, Sunset Rooftop offers breathtaking panoramic views of Cairo's skyline. This venue is perfect for intimate weddings, allowing couples to celebrate under the magical hues of sunset.",
        "contact": "sunset@rooftopvenue.com",
        "venueType": "Rooftop",
        "latitude": 29.9312,
        "longitude": 31.2061,
        "images": [
            "/garden1.jpg",
            "/garden2.jpg",
            "/garden3.jpg",
            "/garden2.jpg"
        ]
    },

    {
        "id": 6,
        "name": "Vintage Chapel",
        "capacity": 120,
        "indoorOutdoor": "Indoor",
        "priceVenue": 3500,
        "priceBar": 1200,
        "priceCeremony": 600,
        "image": "/venue1.jpg",
        "cateringIncluded": false,
        "cleanUpIncluded": true,
        "roomsIncluded": false,
        "location": "Alexandria, Egypt",
        "availability": "Available",
        "rate": 4.4,
        "description": "Located in the historic city of Alexandria, Vintage Chapel provides a charming backdrop for intimate ceremonies. Its classic architecture and warm atmosphere create a romantic setting for your special day.",
        "contact": "info@vintagechapel.com",
        "venueType": "Chapel",
        "latitude": 31.2156,
        "longitude": 29.9553,
        "images": [
            "/ocean1.jpg",
            "/ocean2.jpg",
            "/ocean3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 7,
        "name": "Lakeside Pavilion",
        "capacity": 250,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 4500,
        "priceBar": 1700,
        "priceCeremony": 800,
        "image": "/venue2.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Aswan, Egypt",
        "availability": "Available",
        "rate": 4.8,
        "description": "Surrounded by the tranquil waters of Lake Nasser, Lakeside Pavilion offers a stunning outdoor venue for couples looking to tie the knot amidst nature's beauty. It’s perfect for both ceremonies and receptions.",
        "contact": "contact@lakesidepavilion.com",
        "venueType": "Pavilion",
        "latitude": 24.0955,
        "longitude": 32.8982,
        "images": [
            "/barn1.jpg",
            "/barn2.jpg",
            "/barn3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 8,
        "name": "Modern Gallery",
        "capacity": 180,
        "indoorOutdoor": "Indoor",
        "priceVenue": 6000,
        "priceBar": 1900,
        "priceCeremony": 500,
        "image": "/venue1.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": false,
        "location": "Downtown Cairo, Egypt",
        "availability": "Not Available",
        "rate": 4.6,
        "description": "A contemporary gallery space located in the heart of Downtown Cairo, Modern Gallery is ideal for modern couples looking for a stylish venue. The artistic ambiance and flexible layout allow for creative wedding setups.",
        "contact": "info@moderngallery.com",
        "venueType": "Gallery",
        "latitude": 30.0444,
        "longitude": 31.2357,
        "images": [
            "/elegant1.jpg",
            "/elegant2.jpg",
            "/elegant3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 9,
        "name": "Charming Cottage",
        "capacity": 60,
        "indoorOutdoor": "Indoor",
        "priceVenue": 2000,
        "priceBar": 800,
        "priceCeremony": 300,
        "image": "/venue2.jpg",
        "cateringIncluded": false,
        "cleanUpIncluded": true,
        "roomsIncluded": false,
        "location": "Giza, Egypt",
        "availability": "Available",
        "rate": 4.5,
        "description": "Charming Cottage, located near the Giza Pyramids, offers a cozy and intimate setting for small weddings. With its rustic charm and beautiful garden, it’s perfect for couples looking for a private celebration.",
        "contact": "info@charmingcottage.com",
        "venueType": "Cottage",
        "latitude": 29.9753,
        "longitude": 31.1342,
        "images": [
            "/ocean1.jpg",
            "/ocean2.jpg",
            "/ocean3.jpg",
            "/garden2.jpg"
        ]

    },
    {
        "id": 10,
        "name": "Royal Ballroom",
        "capacity": 350,
        "indoorOutdoor": "Indoor",
        "priceVenue": 8000,
        "priceBar": 3000,
        "priceCeremony": 1000,
        "image": "/venue3.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Cairo, Egypt",
        "availability": "Available",
        "rate": 4.9,
        "description": "Royal Ballroom is a grand venue that epitomizes luxury and elegance. With its high ceilings and exquisite decor, it is the perfect choice for lavish weddings and grand celebrations.",
        "contact": "info@royalballroom.com",
        "venueType": "Ballroom",
        "latitude": 30.0444,
        "longitude": 31.2357,
        "images": [
            "/elegant1.jpg",
            "/elegant2.jpg",
            "/elegant3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 11,
        "name": "Countryside Ranch",
        "capacity": 220,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 3500,
        "priceBar": 1500,
        "priceCeremony": 600,
        "image": "/venue4.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Mansoura, Egypt",
        "availability": "Available",
        "rate": 4.7,
        "description": "Set in the beautiful countryside of Mansoura, this ranch venue combines rustic charm with natural beauty. It’s perfect for outdoor ceremonies and offers ample space for guests to enjoy.",
        "contact": "contact@countrysideranch.com",
        "venueType": "Ranch",
        "latitude": 31.0376,
        "longitude": 31.3640,
        "images": [
            "/barn1.jpg",
            "/barn2.jpg",
            "/barn3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 12,
        "name": "Skyline Terrace",
        "capacity": 100,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 4500,
        "priceBar": 1600,
        "priceCeremony": 400,
        "image": "/venue5.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": false,
        "roomsIncluded": false,
        "location": "Cairo, Egypt",
        "availability": "Available",
        "rate": 4.7,
        "description": "Skyline Terrace offers a breathtaking view of Cairo’s skyline, making it an ideal venue for couples who want to celebrate their special day in a chic and stylish setting. Perfect for sunset ceremonies.",
        "contact": "info@skyline.com",
        "venueType": "Terrace",
        "latitude": 30.0595,
        "longitude": 31.2497,
        "images": [
            "/elegant1.jpg",
            "/elegant2.jpg",
            "/elegant3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 13,
        "name": "Seaside Deck",
        "capacity": 200,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 5000,
        "priceBar": 1800,
        "priceCeremony": 700,
        "image": "/venue1.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Sharm El Sheikh, Egypt",
        "availability": "Not Available",
        "rate": 4.8,
        "description": "Located in the picturesque Sharm El Sheikh, Seaside Deck offers stunning views of the Red Sea. This venue is perfect for beach weddings, providing a beautiful backdrop for your special day.",
        "contact": "info@seasidedck.com",
        "venueType": "Deck",
        "latitude": 27.9159,
        "longitude": 34.3258,
        "images": [
            "/garden1.jpg",
            "/garden2.jpg",
            "/garden3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 14,
        "name": "Historic Castle",
        "capacity": 300,
        "indoorOutdoor": "Indoor",
        "priceVenue": 10000,
        "priceBar": 4000,
        "priceCeremony": 1500,
        "image": "/venue2.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Luxor, Egypt",
        "availability": "Available",
        "rate": 5.0,
        "description": "Experience a fairytale wedding at the Historic Castle in Luxor. With its stunning architecture and rich history, this venue offers an enchanting atmosphere perfect for grand celebrations.",
        "contact": "info@historiccastle.com",
        "venueType": "Castle",
        "latitude": 25.6872,
        "longitude": 32.6396,
        "images": [
            "/ocean1.jpg",
            "/ocean2.jpg",
            "/ocean3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 15,
        "name": "Beachfront Resort",
        "capacity": 250,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 6000,
        "priceBar": 2500,
        "priceCeremony": 900,
        "image": "/venue3.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Marsa Alam, Egypt",
        "availability": "Available",
        "rate": 4.9,
        "description": "Situated along the beautiful coastline of Marsa Alam, this beachfront resort offers a stunning setting for tropical weddings. Enjoy the sound of waves and the beauty of nature on your special day.",
        "contact": "info@beachfrontresort.com",
        "venueType": "Resort",
        "latitude": 25.0216,
        "longitude": 34.8888,
        "images": [
            "/barn1.jpg",
            "/barn2.jpg",
            "/barn3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 16,
        "name": "Elegant Winery",
        "capacity": 180,
        "indoorOutdoor": "Indoor/Outdoor",
        "priceVenue": 4500,
        "priceBar": 1500,
        "priceCeremony": 600,
        "image": "/venue4.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": false,
        "location": "Nile Valley, Egypt",
        "availability": "Available",
        "rate": 4.7,
        "description": "Set in the picturesque Nile Valley, this elegant winery venue combines the beauty of nature with exquisite wine offerings. Perfect for couples looking for a unique and romantic setting.",
        "contact": "info@elegantwinery.com",
        "venueType": "Winery",
        "latitude": 24.8012,
        "longitude": 32.5360,
        "images": [
            "/elegant1.jpg",
            "/elegant2.jpg",
            "/elegant3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 17,
        "name": "Mountain Lodge",
        "capacity": 120,
        "indoorOutdoor": "Indoor/Outdoor",
        "priceVenue": 3500,
        "priceBar": 1200,
        "priceCeremony": 400,
        "image": "/venue5.jpg",
        "cateringIncluded": false,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Mount Sinai, Egypt",
        "availability": "Available",
        "rate": 4.6,
        "description": "Nestled in the scenic Mount Sinai region, this cozy lodge provides a warm and inviting atmosphere for weddings. Surrounded by mountains, it’s perfect for couples who appreciate nature’s beauty.",
        "contact": "info@mountainlodge.com",
        "venueType": "Lodge",
        "latitude": 28.5350,
        "longitude": 33.9757,
        "images": [
            "/garden1.jpg",
            "/garden2.jpg",
            "/garden3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 18,
        "name": "City Park Pavilion",
        "capacity": 200,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 3000,
        "priceBar": 1000,
        "priceCeremony": 500,
        "image": "/venue1.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": false,
        "roomsIncluded": false,
        "location": "Al-Azhar Park, Cairo, Egypt",
        "availability": "Available",
        "rate": 4.5,
        "description": "City Park Pavilion is located in the beautiful Al-Azhar Park, offering a serene atmosphere for weddings. With lush gardens and stunning views of Cairo, it’s an ideal choice for outdoor celebrations.",
        "contact": "info@cityparkpavilion.com",
        "venueType": "Pavilion",
        "latitude": 30.0342,
        "longitude": 31.2364,
        "images": [
            "/ocean1.jpg",
            "/ocean2.jpg",
            "/ocean3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 19,
        "name": "Art Deco Venue",
        "capacity": 220,
        "indoorOutdoor": "Indoor",
        "priceVenue": 5000,
        "priceBar": 2000,
        "priceCeremony": 800,
        "image": "/venue2.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Cairo, Egypt",
        "availability": "Not Available",
        "rate": 4.8,
        "description": "Art Deco Venue offers a stylish and sophisticated atmosphere, perfect for modern weddings. With its unique architectural design and elegant decor, it creates a memorable setting for your celebration.",
        "contact": "info@artdecovenue.com",
        "venueType": "Art Deco",
        "latitude": 30.0453,
        "longitude": 31.2357,
        "images": [
            "/barn1.jpg",
            "/barn2.jpg",
            "/barn3.jpg",
            "/garden2.jpg"
        ]
    },
    {
        "id": 20,
        "name": "Serene Spa Resort",
        "capacity": 160,
        "indoorOutdoor": "Outdoor",
        "priceVenue": 4000,
        "priceBar": 1400,
        "priceCeremony": 600,
        "image": "/venue3.jpg",
        "cateringIncluded": true,
        "cleanUpIncluded": true,
        "roomsIncluded": true,
        "location": "Giza, Egypt",
        "availability": "Available",
        "rate": 4.7,
        "description": "Located in Giza, Serene Spa Resort offers a tranquil setting for weddings. With beautiful gardens and luxurious amenities, it’s perfect for couples looking for a relaxing and elegant venue.",
        "contact": "info@serenespa.com",
        "venueType": "Spa Resort",
        "latitude": 29.9772,
        "longitude": 31.1345,
        "images": [
            "/elegant1.jpg",
            "/elegant2.jpg",
            "/elegant3.jpg",
            "/garden2.jpg"
        ]
    }
];